var battleRoyaleData = [
    {
        "id": "Doge's Battle Royale",
        "name": "Doge's Battle Royale",
        "imageUrl": "img/icon/BattleRoyale/DogesBattleRoyale.jpg",
        "gameType": "Battle Royale",
        "rating": "4.3",
        "description": "Doge's Battle Royale is a fun battle royale game featuring the famous Doge meme. Drop in, find weapons, and be the last one standing in this adorable yet competitive arena.",
        "keywords": "Doge's Battle Royale, Doge, battle royale, meme",
        "link": "BattleRoyale/Doge_s_Battle_Royale.html",
        "tags": ["doge", "battle royale", "meme", "funny"],
        "iframeUrl": "https://html5.gamedistribution.com/f7106e2740504e31be69410a12304172/?gd_sdk_referrer_url=https%3A%2F%2Fwww.onlinegames.io%2Fcat-runner%2F"
    },
    {
        "id": "Battle Royale Noob vs Pro",
        "name": "Battle Royale Noob vs Pro",
        "imageUrl": "img/icon/BattleRoyale/BattleRoyaleNoobvsPro.jpeg",
        "gameType": "Battle Royale",
        "rating": "4.4",
        "description": "Battle Royale Noob vs Pro is an exciting online game that combines battle royale gameplay with fun Noob vs Pro characters. Choose from Noob, Pro, Hacker, or God characters.",
        "keywords": "Battle Royale Noob vs Pro, Noob vs Pro, battle royale, survival",
        "link": "BattleRoyale/Battle_Royale_Noob_vs_Pro.html",
        "tags": ["battle royale noob vs pro", "noob vs pro", "battle royale"],
        "iframeUrl": "https://html5.gamedistribution.com/ab052df5478e46f3b8907dce6799a88f/?gd_sdk_referrer_url=https%3A%2F%2Fwww.onlinegames.io%2Fcat-runner%2F"
    },
    {
        "id": "Top Guns IO",
        "name": "Top Guns IO",
        "imageUrl": "img/icon/BattleRoyale/TopGunsIO.jpeg",
        "gameType": "Battle Royale",
        "rating": "4.5",
        "description": "Top Guns IO is an aerial combat battle royale game. Pilot your aircraft and shoot down opponents to become the top gun!",
        "keywords": "Top Guns IO, aerial, combat, jet, battle royale",
        "link": "BattleRoyale/Top_Guns_IO.html",
        "tags": ["top guns io", "aerial combat", "jet", "battle royale"],
        "iframeUrl": "https://html5.gamedistribution.com/a8cdacefc98244c0a23f76eff86b1c60/?gd_sdk_referrer_url=https%3A%2F%2Fwww.onlinegames.io%2Fcat-runner%2F"
    },
    {
        "id": "Battle Royale Puzzles",
        "name": "Battle Royale Puzzles",
        "imageUrl": "img/icon/BattleRoyale/BattleRoyalePuzzles.jpeg",
        "gameType": "Battle Royale",
        "rating": "4.2",
        "description": "Battle Royale Puzzles combines puzzle gameplay with battle royale elements. Solve puzzles to survive and be the last one standing.",
        "keywords": "Battle Royale Puzzles, puzzle, battle royale, survival",
        "link": "BattleRoyale/Battle_Royale_Puzzles.html",
        "tags": ["battle royale puzzles", "puzzle", "battle royale"],
        "iframeUrl": "https://html5.gamedistribution.com/6e40272c0d394ab8b6e4104fd4692d51/?gd_sdk_referrer_url=https%3A%2F%2Fwww.onlinegames.io%2Fcat-runner%2F"
    },
    {
        "id": "Battle Royale Coloring Book",
        "name": "Battle Royale Coloring Book",
        "imageUrl": "img/icon/BattleRoyale/BattleRoyaleColoringBook.jpeg",
        "gameType": "Battle Royale",
        "rating": "4.0",
        "description": "Battle Royale Coloring Book combines coloring activities with battle royale fun. Color your favorite characters and battle it out!",
        "keywords": "Battle Royale Coloring Book, coloring, battle royale, creative",
        "link": "BattleRoyale/Battle_Royale_Coloring_Book.html",
        "tags": ["battle royale coloring book", "coloring", "creative"],
        "iframeUrl": "https://html5.gamedistribution.com/bb7b60d5cf1f4cca9b3009726246cf69/?gd_sdk_referrer_url=https%3A%2F%2Fwww.onlinegames.io%2Fcat-runner%2F"
    },
    {
        "id": "Battle Royale Jigsaw",
        "name": "Battle Royale Jigsaw",
        "imageUrl": "img/icon/BattleRoyale/BattleRoyaleJigsaw.jpeg",
        "gameType": "Battle Royale",
        "rating": "4.1",
        "description": "Battle Royale Jigsaw is a puzzle game featuring battle royale themes. Complete jigsaw puzzles to unlock new challenges.",
        "keywords": "Battle Royale Jigsaw, jigsaw, puzzle, battle royale",
        "link": "BattleRoyale/Battle_Royale_Jigsaw.html",
        "tags": ["battle royale jigsaw", "jigsaw", "puzzle"],
        "iframeUrl": "https://html5.gamedistribution.com/4cb0cfaad7f04b71a4316d54b418f089/?gd_sdk_referrer_url=https%3A%2F%2Fwww.onlinegames.io%2Fcat-runner%2F"
    },
    {
        "id": "Cube Battle Royale",
        "name": "Cube Battle Royale",
        "imageUrl": "img/icon/BattleRoyale/CubeBattleRoyale.jpeg",
        "gameType": "Battle Royale",
        "rating": "4.6",
        "description": "Cube Battle Royale is a blocky battle royale game. Drop into a cubic arena, gather resources, and battle to be the last cube standing.",
        "keywords": "Cube Battle Royale, cube, blocky, battle royale, Minecraft-style",
        "link": "BattleRoyale/Cube_Battle_Royale.html",
        "tags": ["cube battle royale", "cube", "blocky", "minecraft"],
        "iframeUrl": "https://html5.gamedistribution.com/5d4d5247537c4009af6104a6a1b20323/?gd_sdk_referrer_url=https%3A%2F%2Fwww.onlinegames.io%2Fcat-runner%2F"
    },
    {
        "id": "Battle Royale Puzzle Challenge",
        "name": "Battle Royale Puzzle Challenge",
        "imageUrl": "img/icon/BattleRoyale/BattleRoyalePuzzleChallenge.jpeg",
        "gameType": "Battle Royale",
        "rating": "4.3",
        "description": "Battle Royale Puzzle Challenge tests your puzzle-solving skills in a battle royale setting. Compete against others to solve puzzles first!",
        "keywords": "Battle Royale Puzzle Challenge, puzzle challenge, battle royale",
        "link": "BattleRoyale/Battle_Royale_Puzzle_Challenge.html",
        "tags": ["battle royale puzzle challenge", "puzzle", "challenge"],
        "iframeUrl": "https://html5.gamedistribution.com/0e462cb3e0804b4dbb34878b7bd1c17e/?gd_sdk_referrer_url=https%3A%2F%2Fwww.onlinegames.io%2Fcat-runner%2F"
    },
    {
        "id": "Pixel Battle Royale Multiplayer",
        "name": "Pixel Battle Royale Multiplayer",
        "imageUrl": "img/icon/BattleRoyale/PixelBattleRoyaleMultiplayer.jpeg",
        "gameType": "Battle Royale",
        "rating": "4.4",
        "description": "Pixel Battle Royale Multiplayer is a pixelated battle royale game with multiplayer support. Fight against other players in retro-style arenas.",
        "keywords": "Pixel Battle Royale, pixel, multiplayer, battle royale, retro",
        "link": "BattleRoyale/Pixel_Battle_Royale_Multiplayer.html",
        "tags": ["pixel battle royale", "pixel", "multiplayer", "retro"],
        "iframeUrl": "https://html5.gamedistribution.com/32bad42c0e3d43f9b2fbcf104e6a710e/?gd_sdk_referrer_url=https%3A%2F%2Fwww.onlinegames.io%2Fcat-runner%2F"
    },
    {
        "id": "Pixel Battle Royale",
        "name": "Pixel Battle Royale",
        "imageUrl": "img/icon/BattleRoyale/PixelBattleRoyale.jpeg",
        "gameType": "Battle Royale",
        "rating": "4.2",
        "description": "Pixel Battle Royale is a retro-style battle royale game. Experience the nostalgia of pixel graphics while competing in battle royale matches.",
        "keywords": "Pixel Battle Royale, pixel, battle royale, retro",
        "link": "BattleRoyale/Pixel_Battle_Royale.html",
        "tags": ["pixel battle royale", "pixel", "retro", "battle royale"],
        "iframeUrl": "https://html5.gamedistribution.com/b798bda4908e4424b18af068e26eb5f0/?gd_sdk_referrer_url=https%3A%2F%2Fwww.onlinegames.io%2Fcat-runner%2F"
    }
]